blank_issues_enabled: true
contact_links:
  - name: sfcc-ci channel Unofficial Slack
    url: https://github.com/sfcc-unofficial/docs
    about: Community help can be found on the CC Unofficial Slack in the \#sfcc-ci channel
